// Code generated by templ@v0.2.186 DO NOT EDIT.

package made

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"

func Alert(text string) templ.ComponentScript {
	return templ.ComponentScript{
		Name: `__templ_Alert_1e97`,
		Function: `function __templ_Alert_1e97(text){alert(text);}`,
		Call: templ.SafeScript(`__templ_Alert_1e97`, text),
	}
}

