// Code generated by templ@v0.2.186 DO NOT EDIT.

package made

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"

func Alert(text string) templ.ComponentScript {
	return templ.ComponentScript{
		Name: `__templ_Alert_1e97`,
		Function: `function __templ_Alert_1e97(text){alert(text);}`,
		Call: templ.SafeScript(`__templ_Alert_1e97`, text),
	}
}

func ConsoleLog(text string) templ.ComponentScript {
	return templ.ComponentScript{
		Name: `__templ_ConsoleLog_25ce`,
		Function: `function __templ_ConsoleLog_25ce(text){console.log(text);}`,
		Call: templ.SafeScript(`__templ_ConsoleLog_25ce`, text),
	}
}

func ConsoleError(text string) templ.ComponentScript {
	return templ.ComponentScript{
		Name: `__templ_ConsoleError_0163`,
		Function: `function __templ_ConsoleError_0163(text){console.error(text);}`,
		Call: templ.SafeScript(`__templ_ConsoleError_0163`, text),
	}
}

